spring.application.name=DoAnWeb_65134116_NguyenHuynhTuong
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/quan_com_tam_adou?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html; charset=UTF-8